[workspace]
members = ["core", "android", "ios", "server"]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2024"
authors = ["Albin Sj√∂gren <albin@malmo.skaggbyran.se>"]
license = "GPL-3"

[workspace.dependencies]
rust_decimal = { version = "1.40.0", features = ["serde"] }
dioxus = { version = "0.7.2", features = ["desktop", "router"] }
arrow = { version = "57.2" }
parquet = "57.2"
rayon = "1.11.0"
nalgebra = "0.34.1"