[package]
name = "amp"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.14.0"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
#rusty_math = "0.7.0"
get_fields = "0.1.0"