[application]
name = "amp"
version = "1.0.0"

[bundle]
publisher = "Skäggbyrån Malmö"
icon = ["android/assets/icon/icon-512.png"]
resources = ["android/assets/data/adress_info.parquet"]

[android]
targets = ["arm64-v8a", "arm64-v7a"]
min_sdk = 24
target_sdk = 36