[package]
name = "amp-android"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
amp-core = { path = "../core" }
dioxus.workspace = true
dioxus-native.workspace = true
dioxus-free-icons.workspace = true
chrono.workspace = true
jni.workspace = true
anyhow.workspace = true

[features]
default = ["mobile"]
mobile = ["dioxus/mobile"]

[[bin]]
name = "amp"
path = "src/main.rs"
