[package]
name = "amp-android"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
amp-core = { path = "../core" }
dioxus.workspace = true
serde.workspace = true
serde_json.workspace = true
rust_decimal.workspace = true

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
web = ["dioxus/web"]

[[bin]]
name = "amp"
path = "src/main.rs"
