[package]
name = "amp-android"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
amp-core = { path = "../core" }
dioxus.workspace = true
dioxus-free-icons.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
jni.workspace = true
anyhow.workspace = true
strsim.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
arrow.workspace = true
parquet.workspace = true
bytes.workspace = true
tokio.workspace = true

[features]
default = ["mobile"]
mobile = ["dioxus/mobile"]

[[bin]]
name = "amp"
path = "src/main.rs"
