[package]
name = "amp-jsonfix"
version = "0.1.0"
edition = "2024"

[dependencies]
#serde_json = "1.0.145"
#nestify = "0.3.3"
geojson = "0.24.2"
serde = { version = "1.0.228", features = ["derive"] }
geo-types = "0.7.18"