[package]
name = "debug_script"
edition = "2024"

[dependencies]
amp-core = { path = "../core" }
rust_decimal.workspace = true
parquet.workspace = true

[[bin]]
name = "debug_script"
path = "src/main.rs"